name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:  # Часть CI
    runs-on: ubuntu-latest  # Указываем на каком раннере запускать наши job
    steps:
      # Далее описываются команды, выполняемые внутри секции workflow
#      - name: list dir
#        run: ls -la  # Распечатать текущую директорию
      - name: clone code
        uses: actions/checkout@v2  # Использ. код, разраббот. до нас
      - name: docker build
        run: docker build -t georgiyshvets/sky_pro_homework:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push georgiyshvets/sky_pro_homework:$GITHUB_REF_NAME-$GITHUB_RUN_ID